### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Freakwill** [nusr/FBIWarning#3]
这是报错信息

```
internal/modules/cjs/loader.js:710
    throw err;
    ^

SyntaxError: /Users/william/Programming/myGithub/FBIWarning/socks.json: Unexpected token / in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:707:27)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/william/Programming/myGithub/FBIWarning/main.js:39:22)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! FBIWarning@0.1.0 dev: `node ./index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the FBIWarning@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/william/.npm/_logs/2018-10-28T11_23_58_866Z-debug.log
```

**Comment by nusr** [comment]
@Freakwill   socks.json格式不正确，不符合json 格式

**Comment by Freakwill** [comment]
> @Freakwill socks.json格式不正确，不符合json 格式

改好了(我只是把另一个配置注释掉而已，现在直接删掉了)。现在，没有报错了，但是除了那两行，没有输出，result里面什么也没有。
```json
{
  "port": 57996,
  "host": "127.0.0.1"
}
```

**Comment by nusr** [comment]
@Freakwill   直接访问爱城吧，main.js里有链接

**Comment by Freakwill** [comment]
刚才 http://www.ac168.info/bt/ 打不开了，不知道是什么原因，代理是开着的，也可以翻墙

**Comment by Freakwill** [comment]
现在的地址是http://www.ac168.win, 不过要注册。
